import type { FetchLike, GoogleOAuthService } from "./google-oauth.js";
export interface DriveFile { id: string; name: string; mimeType: string; modifiedTime: string; createdTime?: string; parents: string[]; }
const DRIVE_URL = "https://www.googleapis.com/drive/v3/files";
const escapeQuery = (value: string) => value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
export class GoogleDriveClient {
  constructor(private readonly userId: string, private readonly oauth: GoogleOAuthService, private readonly fetcher: FetchLike = fetch) {}
  private async request(path: string, init: RequestInit = {}): Promise<Response> { const token = await this.oauth.accessToken(this.userId); const response = await this.fetcher(`${DRIVE_URL}${path}`, { ...init, headers: { ...init.headers, authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(response.status === 401 ? "Your Google connection needs to be reconnected." : "Google Drive could not complete that action."); return response; }
  async searchFiles(query: string, foldersOnly = false, signal?: AbortSignal): Promise<DriveFile[]> { const terms = query.trim().split(/\s+/).filter(Boolean).slice(0, 6); const nameQuery = terms.length ? terms.map((term) => `name contains '${escapeQuery(term)}'`).join(" and ") : ""; const q = ["trashed = false", foldersOnly ? "mimeType = 'application/vnd.google-apps.folder'" : "", nameQuery].filter(Boolean).join(" and "); const params = new URLSearchParams({ q, orderBy: "modifiedTime desc", pageSize: "20", fields: "files(id,name,mimeType,modifiedTime,createdTime,parents)" }); const response = await this.request(`?${params}`, { signal }); return (await response.json() as { files?: DriveFile[] }).files ?? []; }
  async getFile(id: string, signal?: AbortSignal): Promise<DriveFile> { const response = await this.request(`/${encodeURIComponent(id)}?fields=id,name,mimeType,modifiedTime,createdTime,parents`, { signal }); return response.json() as Promise<DriveFile>; }
  async renameFile(id: string, name: string, signal?: AbortSignal): Promise<DriveFile> { const response = await this.request(`/${encodeURIComponent(id)}?fields=id,name,mimeType,modifiedTime,createdTime,parents`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }), signal }); return response.json() as Promise<DriveFile>; }
  async moveFile(id: string, folderId: string, signal?: AbortSignal): Promise<DriveFile> { const current = await this.getFile(id, signal); const params = new URLSearchParams({ addParents: folderId, removeParents: current.parents.join(","), fields: "id,name,mimeType,modifiedTime,createdTime,parents" }); const response = await this.request(`/${encodeURIComponent(id)}?${params}`, { method: "PATCH", signal }); return response.json() as Promise<DriveFile>; }
}
