import { createHash, randomBytes } from "node:crypto";

export interface GoogleConnection { userId: string; accessToken: string; refreshToken?: string; expiresAt: Date; scopes: string[]; }
export interface GoogleConnectionStore { save(connection: GoogleConnection): Promise<void>; get(userId: string): Promise<GoogleConnection | undefined>; remove(userId: string): Promise<void>; }
export interface OAuthStateStore { put(state: string, userId: string, expiresAt: Date): Promise<void>; consume(state: string): Promise<{ userId: string } | undefined>; }
export interface GoogleOAuthConfig { clientId: string; clientSecret: string; redirectUri: string; }
export interface FetchLike { (input: string, init?: RequestInit): Promise<Response>; }
const AUTHORIZE_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN_URL = "https://oauth2.googleapis.com/token";
const scopes = ["https://www.googleapis.com/auth/drive"];
const digest = (value: string) => createHash("sha256").update(value).digest("base64url");
export class GoogleOAuthService {
  constructor(private readonly config: GoogleOAuthConfig, private readonly states: OAuthStateStore, private readonly connections: GoogleConnectionStore, private readonly fetcher: FetchLike = fetch) {}
  async authorizationUrl(userId: string): Promise<string> { const state = randomBytes(32).toString("base64url"); await this.states.put(digest(state), userId, new Date(Date.now() + 10 * 60_000)); const params = new URLSearchParams({ client_id: this.config.clientId, redirect_uri: this.config.redirectUri, response_type: "code", access_type: "offline", prompt: "consent", scope: scopes.join(" "), state }); return `${AUTHORIZE_URL}?${params}`; }
  async complete(state: string, code: string): Promise<string> { const record = await this.states.consume(digest(state)); if (!record) throw new Error("Invalid or expired OAuth state."); const body = new URLSearchParams({ code, client_id: this.config.clientId, client_secret: this.config.clientSecret, redirect_uri: this.config.redirectUri, grant_type: "authorization_code" }); const response = await this.fetcher(TOKEN_URL, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); if (!response.ok) throw new Error("Google authorization could not be completed."); const token = await response.json() as { access_token: string; refresh_token?: string; expires_in: number; scope?: string }; await this.connections.save({ userId: record.userId, accessToken: token.access_token, refreshToken: token.refresh_token, expiresAt: new Date(Date.now() + token.expires_in * 1000), scopes: token.scope?.split(" ") ?? scopes }); return record.userId; }
  async accessToken(userId: string): Promise<string> { const connection = await this.connections.get(userId); if (!connection) throw new Error("Google Drive is not connected."); if (connection.expiresAt.getTime() > Date.now() + 60_000) return connection.accessToken; if (!connection.refreshToken) throw new Error("Your Google connection needs to be reconnected."); const body = new URLSearchParams({ client_id: this.config.clientId, client_secret: this.config.clientSecret, refresh_token: connection.refreshToken, grant_type: "refresh_token" }); const response = await this.fetcher(TOKEN_URL, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); if (!response.ok) { await this.connections.remove(userId); throw new Error("Your Google connection needs to be reconnected."); } const token = await response.json() as { access_token: string; expires_in: number }; await this.connections.save({ ...connection, accessToken: token.access_token, expiresAt: new Date(Date.now() + token.expires_in * 1000) }); return token.access_token; }
  disconnect(userId: string): Promise<void> { return this.connections.remove(userId); }
}
