import assert from "node:assert/strict";
import test from "node:test";
import { GoogleDriveClient } from "../src/server/google-drive.js";
import { GoogleOAuthService, type GoogleConnection, type GoogleConnectionStore, type OAuthStateStore } from "../src/server/google-oauth.js";
import { createGoogleDriveTools } from "../src/server/google-workspace.js";

class States implements OAuthStateStore { entries = new Map<string, { userId: string }>(); async put(state: string, userId: string): Promise<void> { this.entries.set(state, { userId }); } async consume(state: string): Promise<{ userId: string } | undefined> { const value = this.entries.get(state); this.entries.delete(state); return value; } }
class Connections implements GoogleConnectionStore { entries = new Map<string, GoogleConnection>(); async save(value: GoogleConnection): Promise<void> { this.entries.set(value.userId, value); } async get(userId: string): Promise<GoogleConnection | undefined> { return this.entries.get(userId); } async remove(userId: string): Promise<void> { this.entries.delete(userId); } }
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
const oauth = (connections = new Connections(), fetcher = async () => response({ access_token: "fresh", expires_in: 3600 })) => new GoogleOAuthService({ clientId: "id", clientSecret: "secret", redirectUri: "https://nexus.test/callback" }, new States(), connections, fetcher);
test("OAuth state is one-time and binds the callback to its initiating user", async () => { const states = new States(); const connections = new Connections(); const service = new GoogleOAuthService({ clientId: "id", clientSecret: "secret", redirectUri: "https://nexus.test/callback" }, states, connections, async () => response({ access_token: "access", refresh_token: "refresh", expires_in: 3600 })); const url = new URL(await service.authorizationUrl("user-a")); await assert.rejects(() => service.complete("tampered", "code"), /state/); await service.complete(url.searchParams.get("state")!, "code"); assert.equal((await connections.get("user-a"))?.accessToken, "access"); await assert.rejects(() => service.complete(url.searchParams.get("state")!, "code"), /state/); });
test("expired tokens refresh server-side and failed refresh disconnects", async () => { const connections = new Connections(); await connections.save({ userId: "a", accessToken: "old", refreshToken: "refresh", expiresAt: new Date(0), scopes: [] }); assert.equal(await oauth(connections).accessToken("a"), "fresh"); await connections.save({ ...(await connections.get("a"))!, expiresAt: new Date(0) }); const failing = oauth(connections, async () => response({}, 400)); await assert.rejects(() => failing.accessToken("a"), /reconnected/); assert.equal(await connections.get("a"), undefined); });
test("Drive client performs authenticated search, rename, move, and reads current state for verification", async () => { const connections = new Connections(); await connections.save({ userId: "user-a", accessToken: "token", expiresAt: new Date(Date.now() + 600_000), scopes: [] }); const calls: Array<{ url: string; init?: RequestInit }> = []; const fetcher = async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.includes("?q=")) return response({ files: [{ id: "f", name: "Invoice", mimeType: "application/pdf", modifiedTime: "2026-09-01", parents: ["old"] }] }); if (init?.method === "PATCH") return response({ id: "f", name: "September Invoice", mimeType: "application/pdf", modifiedTime: "2026-09-02", parents: ["finance"] }); return response({ id: "f", name: "September Invoice", mimeType: "application/pdf", modifiedTime: "2026-09-02", parents: ["finance"] }); }; const drive = new GoogleDriveClient("user-a", oauth(connections), fetcher); const [search, get, rename, move] = createGoogleDriveTools(drive); const context = { executionId: "run", idempotencyKey: "key", mode: "real" as const }; assert.equal((await search!.execute({ query: "latest invoice" }, context)).success, true); const renamed = await rename!.execute({ fileId: "f", name: "September Invoice" }, context); assert.equal((await rename!.verify!({ fileId: "f", name: "September Invoice" }, renamed, context)).verified, true); const moved = await move!.execute({ fileId: "f", folderId: "finance" }, context); assert.equal((await move!.verify!({ fileId: "f", folderId: "finance" }, moved, context)).verified, true); assert.ok(calls.every((call) => call.init?.headers && new Headers(call.init.headers).get("authorization") === "Bearer token")); assert.ok(get); });
test("Drive tools reject malformed write arguments and are scoped to the client user", async () => { const connections = new Connections(); const drive = new GoogleDriveClient("user-a", oauth(connections), async () => response({}, 401)); const tools = createGoogleDriveTools(drive); const rename = tools.find((tool) => tool.id === "drive.rename")!; assert.equal(rename.inputSchema({ fileId: "f", name: "../bad" }), false); await assert.rejects(() => drive.getFile("f"), /not connected/); });
